import type {Metadata} from 'next'; import type {Product} from './types'; import {getCategoryById} from './catalog'; import {store} from './store';
export const siteUrl='https://cvecarairig.rs'; export const fallbackBrandName=store.brand; export const fallbackLogoUrl=store.logo;
export function absoluteUrl(url?:string|null){if(!url)return undefined;return url.startsWith('http')?url:`${siteUrl}${url.startsWith('/')?'':'/'}${url}`}
export const canonicalUrl=(path='/')=>`${siteUrl}${path.startsWith('/')?'':'/'}${path}`;
export function cleanMetaDescription(value?:string|null,fallback='Online Cvećara Irig — sveži buketi, aranžmani i dostava cveća u Irigu i okolini.'){const t=(value??fallback).replace(/\s+/g,' ').trim();return t.length<=160?t:`${t.slice(0,157).trimEnd()}...`}
export const getBrandName=()=>store.brand;
export function buildPageMetadata({title,description,path,image,noIndex=false}:{title:string;description:string;path:string;image?:string|null;brandName?:string;type?:'website'|'article';noIndex?:boolean}):Metadata{const d=cleanMetaDescription(description),url=canonicalUrl(path),img=absoluteUrl(image);return{title,description:d,alternates:{canonical:path},robots:{index:!noIndex,follow:true},openGraph:{type:'website',url,siteName:store.brand,title,description:d,locale:'sr_RS',images:img?[{url:img,alt:title}]:undefined},twitter:{card:img?'summary_large_image':'summary',title,description:d,images:img?[img]:undefined}}}
export function buildBreadcrumbJsonLd(items:{name:string;path:string}[]){return{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:items.map((x,i)=>({'@type':'ListItem',position:i+1,name:x.name,item:canonicalUrl(x.path)}))}}
export function buildProductJsonLd(product:Product,imageUrls:string[],productUrl:string,brandName=store.brand){return{'@context':'https://schema.org','@type':'Product',name:product.name,brand:{'@type':'Brand',name:brandName},category:getCategoryById(product.categoryId)?.name,description:product.seoDescription,image:imageUrls,url:productUrl,sku:product.sku,offers:{'@type':'Offer',priceCurrency:'RSD',price:product.priceRsd.toFixed(2),url:productUrl}}}
